version: "3.8"
services:
  job_service:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENDPOINT_EXTRA_SOURCE_SERVICE=http://avatureexternaljobs:8080
    command:
      [
        "uvicorn",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "app.main:app",
      ]

  avatureexternaljobs:
    build:
      context: ./jobberwocky-extra-source/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
